name: Demo workflow

on:
  workflow_dispatch: {}

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: vars
        id: vars
        shell: bash
        run: |
          first_name="John" >> $GITHUB_OUTPUT
          last_name="Doe" >> $GITHUB_OUTPUT

      - name: summary
        if: steps.vars.outputs.first_name == 'John' && steps.vars.outputs.last_name == 'Doe'
        shell: bash
        run: |
          echo 'Hello, ${{ steps.vars.outputs.first_name }} ${{ steps.vars.outputs.last_name }}!' >> $GITHUB_STEP_SUMMARY