name: First workflow

on:
  workflow_dispatch:
    inputs:
        first_name:
            description: First name
            required: true
            type: string
            default: John
        last_name:
            description: Last name
            required: true
            type: string
            default: Doe
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: vars
        id: vars
        shell: bash
        run: |
          echo "custom_var=Something" >> $GITHUB_OUTPUT

      - name: summary on workflow dispatch
        if: steps.vars.outputs.custom_var != '' && inputs.first_name == 'John' && inputs.last_name == 'Doe' && github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          echo 'Hello, ${{ steps.vars.outputs.first_name }} ${{ steps.vars.outputs.last_name }}!' >> $GITHUB_STEP_SUMMARY
