name: First workflow

on:
  workflow_dispatch:
    inputs:
        first_name:
            description: First name
            required: true
            type: string
            default: John
        last_name:
            description: Last name
            required: true
            type: string
            default: Doe
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: vars
        id: vars
        shell: bash
        run: |
          echo "custom_var=Something" >> $GITHUB_OUTPUT
          echo "custom_json={\"key\":\"value\"}" >> $GITHUB_OUTPUT

      - name: summary on workflow dispatch
        if: steps.vars.outputs.custom_var != '' && inputs.first_name == 'John' && inputs.last_name == 'Doe' && github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          echo 'Hello, ${{ inputs.first_name }} ${{ inputs.last_name }}!' >> $GITHUB_STEP_SUMMARY

      - name: json summary
        if: fromJSON(steps.vars.outputs.custom_json).key == 'value'
        shell: bash
        run: |
          echo ''
          echo 'JSON summary' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.vars.outputs.custom_json }} >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: negative condition
        if: ${{ ! fromJSON(steps.vars.outputs.custom_json).key == 'something' }}
        shell: bash
        run: |
          echo ''
          echo 'JSON summary2' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.vars.outputs.custom_json }} >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY